### ISSUE TITLE
i can't download this plugins and cant close export windows

### ISSUE THREAD

**Issue by EasyChris** [ingrammicro/puzzle-publisher#2]
https://github.com/ingrammicro/puzzle-publisher/raw/master/Exporter.sketchplugin.zip

and no release file i can download

**Comment by EasyChris** [comment]
and when i `export select to html`  when export success , it can't close windows
![image](https://user-images.githubusercontent.com/9960087/64500662-aee8ff00-d2f0-11e9-868b-044fdad51642.png)

**Comment by zeljkoprsa** [comment]
@EasyChris Same here, although the files have been successfully exported. I guess it's got something to do with the latest version of Sketch I'm using 57.1.

**Comment by MaxBazarov** [comment]
Sorry,
The valid URL is https://github.com/ingrammicro/puzzle-publisher/raw/master/PuzzlePublisher.sketchplugin.zip <https://github.com/ingrammicro/puzzle-publisher/raw/master/PuzzlePublisher.sketchplugin.zip>
I will fix documentation.

**Comment by MaxBazarov** [comment]
@EasyChris  and @zeljkoprsa,
Could you 
1) run the following command in Terminal:
tail -f ~/Library/Logs/com.bohemiancoding.sketch3/Plugin\ Log.log 
2) run Export to HTML
3) grab log from Terminal and show it to me?

Thanks!

**Comment by zeljkoprsa** [comment]
@MaxBazarov Here it is. Did this before the update I got presented with when opening sketch.

/Users/zeljkoprsa/Desktop/emmezeta-product-mockups/images/previews/
exportArtboards: running...
 collectArtboardsLayers: running...
 collectArtboardsLayers: done!
 resizeLayers: running...
 resizeLayers: done!
 exportImages: running...
  exportArtboardImages: running... 411449-PDCC5H-919
  exportArtboardImages: done!
 exportImages: done!
 compressImages: running...
 **compressImages: failed!**
 buildPreviews: running...
 buildPreviews: done!!!!!
_getLibraries: start
_getLibraries: finish
 SaveToJSON: cleanup before saving...
 SaveToJSON: running...
 SaveToJSON: done!
 reset artboard custom sizes: running...
 reset artboard custom sizes: done...
exportArtboards: done!
closing...
closed

Also, got this error:
![sh](https://user-images.githubusercontent.com/10166/64905189-b899aa80-d6d4-11e9-977f-5a180e0e2991.png)

**Comment by EasyChris** [comment]
this is first log
![image](https://user-images.githubusercontent.com/9960087/64905205-4bebd380-d707-11e9-8ef5-0d104661318c.png)


and when i run  `export html`

```log
🐛🐛🐛 OnOpenDocument 5
🐛🐛🐛 OnOpenDocument 6
🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛 check update
😋😋😋😋😋😋😋😋😋😋😋 READING APPCAST_URL SUCCESSFULLY
😋😋😋😋😋😋😋😋😋😋😋 LASTEST VERSION: 2.16.0
😋😋😋😋😋😋😋😋😋😋😋 CURRENT VERSION: 2.16.0
👀👀👀 image 👀👀👀
<NSImage 0x60000b636140 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004b87a70 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002bd8ce0"
)>
newSelection:
oldSelection:
after autoArrangeLayers
after syncArtboardsToPanel
newSelection:
oldSelection:
after autoArrangeLayers
after syncArtboardsToPanel
newSelection: <MSArtboardGroup: 0x7fcd8a8bdbe0> 首页-v1 (7EA63EF5-E142-4751-84BC-FD87366E6256),<MSArtboardGroup: 0x7fcd8a8be480> 首页-v1-弹窗 (42A37021-4280-4B00-B01A-BDAFC95DAAE3)
oldSelection:
after autoArrangeLayers
after syncArtboardsToPanel
newSelection: <MSArtboardGroup: 0x7fcd8a8bdbe0> 首页-v1 (7EA63EF5-E142-4751-84BC-FD87366E6256)
oldSelection: <MSArtboardGroup: 0x7fcd8a8bdbe0> 首页-v1 (7EA63EF5-E142-4751-84BC-FD87366E6256),<MSArtboardGroup: 0x7fcd8a8be480> 首页-v1-弹窗 (42A37021-4280-4B00-B01A-BDAFC95DAAE3)
💮💮💮💮💮 START TO APPLY LAYER <MSArtboardGroup: 0x7fcd8a8bdbe0> 首页-v1 (7EA63EF5-E142-4751-84BC-FD87366E6256)
parent: <MSPage: 0x7fcd8edc3c90> Page 1 (BD56AC2F-70D7-4FA7-AB7E-A47CED2F4522)
🦁
<MSArtboardGroup: 0x7fcd8a8bdbe0> 首页-v1 (7EA63EF5-E142-4751-84BC-FD87366E6256)
🦁
<MSPage: 0x7fcd8edc3c90> Page 1 (BD56AC2F-70D7-4FA7-AB7E-A47CED2F4522)
💮💮💮💮💮 START TO APPLY LAYER <MSArtboardGroup: 0x7fcd8a8be480> 首页-v1-弹窗 (42A37021-4280-4B00-B01A-BDAFC95DAAE3)
parent: <MSPage: 0x7fcd8edc3c90> Page 1 (BD56AC2F-70D7-4FA7-AB7E-A47CED2F4522)
🦁
<MSArtboardGroup: 0x7fcd8a8be480> 首页-v1-弹窗 (42A37021-4280-4B00-B01A-BDAFC95DAAE3)
🦁
<MSPage: 0x7fcd8edc3c90> Page 1 (BD56AC2F-70D7-4FA7-AB7E-A47CED2F4522)
after autoArrangeLayers
after syncArtboardsToPanel
newSelection:
oldSelection: <MSArtboardGroup: 0x7fcd8a8bdbe0> 首页-v1 (7EA63EF5-E142-4751-84BC-FD87366E6256)
💮💮💮💮💮 START TO APPLY LAYER <MSArtboardGroup: 0x7fcd8a8bdbe0> 首页-v1 (7EA63EF5-E142-4751-84BC-FD87366E6256)
parent: <MSPage: 0x7fcd8edc3c90> Page 1 (BD56AC2F-70D7-4FA7-AB7E-A47CED2F4522)
🦁
<MSArtboardGroup: 0x7fcd8a8bdbe0> 首页-v1 (7EA63EF5-E142-4751-84BC-FD87366E6256)
🦁
<MSPage: 0x7fcd8edc3c90> Page 1 (BD56AC2F-70D7-4FA7-AB7E-A47CED2F4522)
after autoArrangeLayers
after syncArtboardsToPanel
🐛🐛🐛 OnOpenDocument 1
newSelection:
oldSelection:
after autoArrangeLayers
after syncArtboardsToPanel
🐛🐛🐛 OnOpenDocument 2
🐛🐛🐛 OnOpenDocument 3
CHECK RUN_ON_DOCUMENT_OPEN 1
🐛🐛🐛 OnOpenDocument 4
Begin show kitchen toolbar.
Finish check mac version.
Set delegate.
👀👀👀 image 👀👀👀
<NSImage 0x6000088d20c0 Size={2, 2} Reps=(
    "NSBitmapImageRep 0x600004c82620 Size={2, 2} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=2x2 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002cc02c0"
)>
👀👀👀 image 👀👀👀
<NSImage 0x60000882ce40 Size={200, 140} Reps=(
    "NSBitmapImageRep 0x600004c828a0 Size={200, 140} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=200x140 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002c310a0"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088d3b00 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004c828f0 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002cc9aa0"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088db780 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004c8d9a0 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002cf4940"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088de840 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004cae080 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002cfdaa0"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088df000 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004caf8e0 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002cfc500"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088d4d40 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004c8e170 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002ce1a00"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088dfe00 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004c94320 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002ce9da0"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088c8a80 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004c89900 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002cf2be0"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088cd3c0 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004c94640 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002c9c900"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088c9300 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004c89950 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002c91960"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088d5540 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004c8e1c0 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002ce2da0"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088ca980 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004c89c70 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002c91d80"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088cb780 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004c89ea0 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002c908e0"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088c0ec0 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004c829e0 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002cef4c0"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088d5e40 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004c8e300 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002ce3440"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088c1840 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004c82cb0 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002c86960"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088cfac0 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004c950e0 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002c8cd40"
)>
👀👀👀 image 👀👀👀
<NSImage 0x6000088c23c0 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004c82df0 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002c880e0"
)>
🐛🐛🐛 OnOpenDocument 5
🐛🐛🐛 OnOpenDocument 6
newSelection:
oldSelection:
after autoArrangeLayers
after syncArtboardsToPanel
The file “byteorigin” doesn’t exist.
/Users/chrischen/Downloads/Storage/project/steinway/byteOrigin/byteorigin/images/previews/
🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛 check update
😋😋😋😋😋😋😋😋😋😋😋 READING APPCAST_URL SUCCESSFULLY
😋😋😋😋😋😋😋😋😋😋😋 LASTEST VERSION: 2.16.1
😋😋😋😋😋😋😋😋😋😋😋 CURRENT VERSION: 2.16.0
👀👀👀 image 👀👀👀
<NSImage 0x60000ffa9880 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004d110e0 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002d66260"
)>
exportArtboards: running...
name=Page 1
 collectArtboardsLayers: running...
 collectArtboardsLayers: done!
 resizeLayers: running...
 resizeLayers: done!
 exportImages: running...
  exportArtboardImages: running... Desktop HD
  exportArtboardImages: done!
 exportImages: done!
 buildPreviews: running...
👀👀👀 image 👀👀👀
<NSImage 0x60000ff4fcc0 Size={76, 76} Reps=(
    "NSBitmapImageRep 0x600004b4db30 Size={76, 76} ColorSpace=(not yet loaded) BPS=8 BPP=(not yet loaded) Pixels=76x76 Alpha=YES Planar=NO Format=(not yet loaded) CurrentBacking=nil (faulting) CGImageSource=0x600002056b80"
)>
 buildPreviews: done!!!!!
_getLibraries: start
Error: could not get the document: <MOMethod: 0x600002fd4aa0 : target=0x600000e6f480<MSUserAssetLibrary: 0x600000e6f480>, selector=status>
    at value (/Applications/Sketch.app/Contents/Resources/SketchAPI_dom.js:1:151788)
    at _getLibraries (/Users/chrischen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/PuzzlePublisher.sketchplugin/Contents/Sketch/menu-export-html.js:2642:40)
    at saveToJSON (/Users/chrischen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/PuzzlePublisher.sketchplugin/Contents/Sketch/menu-export-html.js:3023:36)
    at exportArtboards (/Users/chrischen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/PuzzlePublisher.sketchplugin/Contents/Sketch/menu-export-html.js:3100:20)
    at /Users/chrischen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/PuzzlePublisher.sketchplugin/Contents/Sketch/menu-export-html.js:3223:54
Could not read image data at /Users/chrischen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/MockingBot.sketchplugin/Contents/Resources/icon.png
```

**Comment by MaxBazarov** [comment]
Ok, I see.please uncheck Compress Images checkbox in the Export to HTML dialog.

Image compression was an experimental feature and seems it doesn’t work stable everywhere.

Отправлено с iPhone

**Comment by MaxBazarov** [comment]
@zeljkoprsa 
Please uncheck Compress Images checkbox in Export to HTML dialog.
Image compression was an experimental feature and seems it's not stable.

**Comment by MaxBazarov** [comment]
@EasyChris 
Please upgrade the plugin to 10.2.2 version.I added additional check for invalid libraries. 
Hope it will resolve your issue!

**Comment by EasyChris** [comment]
@MaxBazarov Thank you very much for solving my problem.

**Comment by MaxBazarov** [comment]
Great to know it!

Отправлено с iPhone

**Comment by zeljkoprsa** [comment]
@MaxBazarov Awesome, it worked well after upgrade. Thanks!
